import { Event, Registration, Ticket, CheckIn, AdminStats } from './types';

export const DEMO_EVENTS: Event[] = [
  {
    id: 'evt-101',
    eventId: 'evt-101',
    name: 'Next-Gen AI Agents & Autonomous Workflows',
    title: 'Next-Gen AI Agents & Autonomous Workflows',
    slug: 'next-gen-ai-agents',
    date: '2026-08-22',
    venue: 'Kaluna Main Stage (Hall A) & Online Stream',
    location: 'Kaluna Main Stage (Hall A) & Online Stream',
    capacity: 150,
    seatsRemaining: 8,
    status: 'Limited',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'evt-102',
    eventId: 'evt-102',
    name: 'Kaluna Salon: Speculative Fiction & Philosophy of Mind',
    title: 'Kaluna Salon: Speculative Fiction & Philosophy of Mind',
    slug: 'kaluna-salon-speculative-fiction',
    date: '2026-08-28',
    venue: 'Kaluna Reading Lounge, 3rd Floor',
    location: 'Kaluna Reading Lounge, 3rd Floor',
    capacity: 50,
    seatsRemaining: 0,
    status: 'Sold Out',
    createdAt: '2026-07-05T14:30:00Z',
  },
  {
    id: 'evt-103',
    eventId: 'evt-103',
    name: 'Hands-on Rust Systems Programming & Memory Safety',
    title: 'Hands-on Rust Systems Programming & Memory Safety',
    slug: 'hands-on-rust-systems',
    date: '2026-09-05',
    venue: 'Kaluna Engineering Lab B',
    location: 'Kaluna Engineering Lab B',
    capacity: 40,
    seatsRemaining: 18,
    status: 'Available',
    createdAt: '2026-07-10T09:15:00Z',
  },
  {
    id: 'evt-104',
    eventId: 'evt-104',
    name: 'Quantum Computing Hardware & Fault-Tolerant Qubits',
    title: 'Quantum Computing Hardware & Fault-Tolerant Qubits',
    slug: 'quantum-computing-hardware',
    date: '2026-09-12',
    venue: 'Auditorium 2 & Streaming',
    location: 'Auditorium 2 & Streaming',
    capacity: 100,
    seatsRemaining: 65,
    status: 'Available',
    createdAt: '2026-07-12T11:00:00Z',
  },
  {
    id: 'evt-105',
    eventId: 'evt-105',
    name: 'Deep Reading in the Digital Age: Micro-Essay Workshop',
    title: 'Deep Reading in the Digital Age: Micro-Essay Workshop',
    slug: 'deep-reading-micro-essay-workshop',
    date: '2026-09-18',
    venue: 'Kaluna Writing Studio',
    location: 'Kaluna Writing Studio',
    capacity: 30,
    seatsRemaining: 12,
    status: 'Available',
    createdAt: '2026-07-15T16:00:00Z',
  },
  {
    id: 'evt-106',
    eventId: 'evt-106',
    name: 'UI/UX Design Systems: Micro-Interactions & Motion Tokens',
    title: 'UI/UX Design Systems: Micro-Interactions & Motion Tokens',
    slug: 'ui-ux-design-systems-motion',
    date: '2026-09-25',
    venue: 'Kaluna Design Studio A',
    location: 'Kaluna Design Studio A',
    capacity: 60,
    seatsRemaining: 2,
    status: 'Limited',
    createdAt: '2026-07-18T08:45:00Z',
  },
];

export const DEMO_REGISTRATIONS: Registration[] = [
  {
    id: 'reg-001',
    eventId: 'evt-101',
    eventTitle: 'Next-Gen AI Agents & Autonomous Workflows',
    userName: 'Alex Mercer',
    userEmail: 'alex.mercer@example.com',
    ticketCode: 'KALUNA-AI-9842',
    registeredAt: '2026-08-01T14:22:10Z',
    status: 'confirmed',
  },
  {
    id: 'reg-002',
    eventId: 'evt-102',
    eventTitle: 'Kaluna Salon: Speculative Fiction & Philosophy of Mind',
    userName: 'Sarah Jenkins',
    userEmail: 'sarah.j@example.com',
    ticketCode: 'KALUNA-BOK-3319',
    registeredAt: '2026-08-02T11:05:40Z',
    status: 'confirmed',
  },
  {
    id: 'reg-003',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    ticketCode: 'KALUNA-WKS-7712',
    registeredAt: '2026-08-03T09:12:00Z',
    status: 'checked_in',
  },
];

export const DEMO_TICKETS: Record<string, Ticket> = {
  'KALUNA-AI-9842': {
    ticketCode: 'KALUNA-AI-9842',
    registrationId: 'reg-001',
    eventId: 'evt-101',
    eventTitle: 'Next-Gen AI Agents & Autonomous Workflows',
    eventDate: '2026-08-22',
    eventTime: '18:00 - 20:30 EST',
    location: 'Kaluna Main Stage (Hall A) & Online Stream',
    userName: 'Alex Mercer',
    userEmail: 'alex.mercer@example.com',
    qrValue: 'KALUNA-AI-9842:evt-101:alex.mercer@example.com',
    status: 'valid',
  },
  'KALUNA-BOK-3319': {
    ticketCode: 'KALUNA-BOK-3319',
    registrationId: 'reg-002',
    eventId: 'evt-102',
    eventTitle: 'Kaluna Salon: Speculative Fiction & Philosophy of Mind',
    eventDate: '2026-08-28',
    eventTime: '19:00 - 21:00 EST',
    location: 'Kaluna Reading Lounge, 3rd Floor',
    userName: 'Sarah Jenkins',
    userEmail: 'sarah.j@example.com',
    qrValue: 'KALUNA-BOK-3319:evt-102:sarah.j@example.com',
    status: 'valid',
  },
  'KALUNA-WKS-7712': {
    ticketCode: 'KALUNA-WKS-7712',
    registrationId: 'reg-003',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    eventDate: '2026-09-05',
    eventTime: '13:00 - 17:00 EST',
    location: 'Kaluna Engineering Lab B',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    qrValue: 'KALUNA-WKS-7712:evt-103:dkim.dev@example.com',
    status: 'used',
    checkedInAt: '2026-08-05T13:02:15Z',
  },
};

export const DEMO_CHECKINS: CheckIn[] = [
  {
    id: 'chk-801',
    ticketCode: 'KALUNA-WKS-7712',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    timestamp: '2026-08-05T13:02:15Z',
    status: 'success',
    note: 'Scanned at Lab B Entrance',
  },
  {
    id: 'chk-802',
    ticketCode: 'KALUNA-WKS-7712',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    timestamp: '2026-08-05T13:08:44Z',
    status: 'already_checked_in',
    note: 'Duplicate scan attempt prevented',
  },
  {
    id: 'chk-803',
    ticketCode: 'INVALID-CODE-0000',
    eventId: 'evt-101',
    eventTitle: 'Next-Gen AI Agents & Autonomous Workflows',
    userName: 'Unknown',
    userEmail: 'unknown@example.com',
    timestamp: '2026-08-05T14:15:30Z',
    status: 'failed',
    note: 'Ticket code invalid or expired',
  },
];

export const DEMO_ADMIN_STATS: AdminStats = {
  totalEvents: 6,
  totalRegistrations: 325,
  totalCheckIns: 184,
  capacityUtilization: 75.6,
  recentRegistrations: DEMO_REGISTRATIONS,
  recentCheckIns: DEMO_CHECKINS,
  categoryBreakdown: [
    { category: 'Tech', count: 2, registrations: 177 },
    { category: 'Books', count: 2, registrations: 68 },
    { category: 'Workshop', count: 2, registrations: 80 },
  ],
};
