import { Event, Registration, Ticket, CheckIn, AdminStats } from './types';

export const DEMO_EVENTS: Event[] = [
  {
    id: 'evt-101',
    title: 'Next-Gen AI Agents & Autonomous Workflows',
    slug: 'next-gen-ai-agents',
    description:
      'Explore the architectural paradigms of multi-agent systems, local LLM orchestration, and deterministic safety bounds in production agentic loops. Featuring live coding of event-driven agent mesh networks.',
    shortDescription:
      'Multi-agent orchestration, local LLM architectures, and deterministic safety bounds.',
    category: 'Tech',
    date: '2026-08-22',
    time: '18:00 - 20:30 EST',
    location: 'Kaluna Main Stage (Hall A) & Online Stream',
    virtualUrl: 'https://live.kaluna.io/evt-101',
    speaker: {
      name: 'Dr. Aris Thorne',
      role: 'Head of AI Systems, Neural Dynamic Systems',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    },
    capacity: 150,
    registeredCount: 142,
    price: 0,
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    tags: ['Artificial Intelligence', 'Multi-Agent', 'LLM', 'Architecture'],
    featured: true,
    status: 'Limited',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'evt-102',
    title: 'Kaluna Salon: Speculative Fiction & Philosophy of Mind',
    slug: 'kaluna-salon-speculative-fiction',
    description:
      'An intimate evening discussing post-human ethics, consciousness, and worldbuilding in modern sci-fi literature. Read along chapter selections from "The Cybernetic Soul" provided prior to the session.',
    shortDescription:
      'Post-human ethics, artificial consciousness, and worldbuilding in sci-fi literature.',
    category: 'Books',
    date: '2026-08-28',
    time: '19:00 - 21:00 EST',
    location: 'Kaluna Reading Lounge, 3rd Floor',
    speaker: {
      name: 'Elena Vance',
      role: 'Author & Literary Critic, Speculative Press',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    },
    capacity: 50,
    registeredCount: 50,
    price: 15,
    imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Literature', 'Philosophy', 'Sci-Fi', 'Book Club'],
    featured: true,
    status: 'Sold Out',
    createdAt: '2026-07-05T14:30:00Z',
  },
  {
    id: 'evt-103',
    title: 'Hands-on Rust Systems Programming & Memory Safety',
    slug: 'hands-on-rust-systems',
    description:
      'Deep dive workshop on low-level async primitives, custom memory allocators, and lock-free data structures in Rust 2024. Participants will build a high-performance TCP event loop from scratch.',
    shortDescription:
      'Async primitives, zero-cost abstractions, and lock-free data structures in Rust.',
    category: 'Workshop',
    date: '2026-09-05',
    time: '13:00 - 17:00 EST',
    location: 'Kaluna Engineering Lab B',
    speaker: {
      name: 'Marcus Chen',
      role: 'Principal Systems Engineer, HighFreq Core',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    },
    capacity: 40,
    registeredCount: 22,
    price: 49,
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    tags: ['Rust', 'Systems', 'Performance', 'Concurrency'],
    featured: false,
    status: 'Available',
    createdAt: '2026-07-10T09:15:00Z',
  },
  {
    id: 'evt-104',
    title: 'Quantum Computing Hardware & Fault-Tolerant Qubits',
    slug: 'quantum-computing-hardware',
    description:
      'A technical breakdown of superconducting transmons vs. ion-trap qubit architectures, error correction code distance scaling, and NISQ-era practical algorithms.',
    shortDescription:
      'Superconducting transmons, topological qubits, and quantum error mitigation.',
    category: 'Tech',
    date: '2026-09-12',
    time: '17:30 - 19:30 EST',
    location: 'Auditorium 2 & Streaming',
    virtualUrl: 'https://live.kaluna.io/evt-104',
    speaker: {
      name: 'Dr. Maya Lin',
      role: 'Quantum Information Scientist',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    },
    capacity: 100,
    registeredCount: 35,
    price: 0,
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=80',
    tags: ['Quantum', 'Hardware', 'Physics', 'Computing'],
    featured: false,
    status: 'Available',
    createdAt: '2026-07-12T11:00:00Z',
  },
  {
    id: 'evt-105',
    title: 'Deep Reading in the Digital Age: Micro-Essay Workshop',
    slug: 'deep-reading-micro-essay-workshop',
    description:
      'Learn how to turn complex analytical notes into crisp, compelling micro-essays. We analyze sentence rhythms, pacing, and editorial precision across modern publications.',
    shortDescription:
      'Analytical note-taking, sentence rhythm, and editorial craft.',
    category: 'Books',
    date: '2026-09-18',
    time: '18:30 - 20:30 EST',
    location: 'Kaluna Writing Studio',
    speaker: {
      name: 'Julian Ross',
      role: 'Editor-in-Chief, Modern Thought Review',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    },
    capacity: 30,
    registeredCount: 18,
    price: 25,
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    tags: ['Writing', 'Essays', 'Editorial', 'Publishing'],
    featured: false,
    status: 'Available',
    createdAt: '2026-07-15T16:00:00Z',
  },
  {
    id: 'evt-106',
    title: 'UI/UX Design Systems: Micro-Interactions & Motion Tokens',
    slug: 'ui-ux-design-systems-motion',
    description:
      'Master the creation of fluid, tactile user interfaces using custom cubic-bezier curves, spring physics, and CSS token systems. Interactive design sprint included.',
    shortDescription:
      'Tactile micro-interactions, cubic-bezier timing, and tokenized design systems.',
    category: 'Workshop',
    date: '2026-09-25',
    time: '14:00 - 18:00 EST',
    location: 'Kaluna Design Studio A',
    speaker: {
      name: 'Sophia Reyes',
      role: 'Lead Design Systems Engineer, Kaluna FX',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    },
    capacity: 60,
    registeredCount: 58,
    price: 35,
    imageUrl: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=1200&q=80',
    tags: ['Design System', 'UI/UX', 'Animation', 'CSS'],
    featured: true,
    status: 'Limited',
    createdAt: '2026-07-18T08:45:00Z',
  },
];

export const DEMO_REGISTRATIONS: Registration[] = [
  {
    id: 'reg-001',
    eventId: 'evt-101',
    eventTitle: 'Next-Gen AI Agents & Autonomous Workflows',
    userName: 'Alex Mercer',
    userEmail: 'alex.mercer@example.com',
    ticketCode: 'KALUNA-AI-9842',
    registeredAt: '2026-08-01T14:22:10Z',
    status: 'confirmed',
  },
  {
    id: 'reg-002',
    eventId: 'evt-102',
    eventTitle: 'Kaluna Salon: Speculative Fiction & Philosophy of Mind',
    userName: 'Sarah Jenkins',
    userEmail: 'sarah.j@example.com',
    ticketCode: 'KALUNA-BOK-3319',
    registeredAt: '2026-08-02T11:05:40Z',
    status: 'confirmed',
  },
  {
    id: 'reg-003',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    ticketCode: 'KALUNA-WKS-7712',
    registeredAt: '2026-08-03T09:12:00Z',
    status: 'checked_in',
  },
];

export const DEMO_TICKETS: Record<string, Ticket> = {
  'KALUNA-AI-9842': {
    ticketCode: 'KALUNA-AI-9842',
    registrationId: 'reg-001',
    eventId: 'evt-101',
    eventTitle: 'Next-Gen AI Agents & Autonomous Workflows',
    eventDate: '2026-08-22',
    eventTime: '18:00 - 20:30 EST',
    location: 'Kaluna Main Stage (Hall A) & Online Stream',
    userName: 'Alex Mercer',
    userEmail: 'alex.mercer@example.com',
    qrValue: 'KALUNA-AI-9842:evt-101:alex.mercer@example.com',
    status: 'valid',
  },
  'KALUNA-BOK-3319': {
    ticketCode: 'KALUNA-BOK-3319',
    registrationId: 'reg-002',
    eventId: 'evt-102',
    eventTitle: 'Kaluna Salon: Speculative Fiction & Philosophy of Mind',
    eventDate: '2026-08-28',
    eventTime: '19:00 - 21:00 EST',
    location: 'Kaluna Reading Lounge, 3rd Floor',
    userName: 'Sarah Jenkins',
    userEmail: 'sarah.j@example.com',
    qrValue: 'KALUNA-BOK-3319:evt-102:sarah.j@example.com',
    status: 'valid',
  },
  'KALUNA-WKS-7712': {
    ticketCode: 'KALUNA-WKS-7712',
    registrationId: 'reg-003',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    eventDate: '2026-09-05',
    eventTime: '13:00 - 17:00 EST',
    location: 'Kaluna Engineering Lab B',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    qrValue: 'KALUNA-WKS-7712:evt-103:dkim.dev@example.com',
    status: 'used',
    checkedInAt: '2026-08-05T13:02:15Z',
  },
};

export const DEMO_CHECKINS: CheckIn[] = [
  {
    id: 'chk-801',
    ticketCode: 'KALUNA-WKS-7712',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    timestamp: '2026-08-05T13:02:15Z',
    status: 'success',
    note: 'Scanned at Lab B Entrance',
  },
  {
    id: 'chk-802',
    ticketCode: 'KALUNA-WKS-7712',
    eventId: 'evt-103',
    eventTitle: 'Hands-on Rust Systems Programming & Memory Safety',
    userName: 'David Kim',
    userEmail: 'dkim.dev@example.com',
    timestamp: '2026-08-05T13:08:44Z',
    status: 'already_checked_in',
    note: 'Duplicate scan attempt prevented',
  },
  {
    id: 'chk-803',
    ticketCode: 'INVALID-CODE-0000',
    eventId: 'evt-101',
    eventTitle: 'Next-Gen AI Agents & Autonomous Workflows',
    userName: 'Unknown',
    userEmail: 'unknown@example.com',
    timestamp: '2026-08-05T14:15:30Z',
    status: 'failed',
    note: 'Ticket code invalid or expired',
  },
];

export const DEMO_ADMIN_STATS: AdminStats = {
  totalEvents: 6,
  totalRegistrations: 325,
  totalCheckIns: 184,
  capacityUtilization: 75.6,
  recentRegistrations: DEMO_REGISTRATIONS,
  recentCheckIns: DEMO_CHECKINS,
  categoryBreakdown: [
    { category: 'Tech', count: 2, registrations: 177 },
    { category: 'Books', count: 2, registrations: 68 },
    { category: 'Workshop', count: 2, registrations: 80 },
  ],
};
